name: ServerSystem
version: 1.7.1
main: me.Entity303.ServerSystem.Main.ss
api-version: 1.13
authors: [Entity303]
load: POSTWORLD
loadbefore:
  - AntiPluginLookUp
  - Vault
softdepend:
  - Essentials
  - PlotSquared
  - Vault
  - PlaceholderAPI
